// universitylist.ts
export const countryCodes = [
  { code: "+93", country: "Afghanistan", flag: "🇦🇫" },
  { code: "+355", country: "Albania", flag: "🇦🇱" },
  { code: "+213", country: "Algeria", flag: "🇩🇿" },
  { code: "+376", country: "Andorra", flag: "🇦🇩" },
  { code: "+244", country: "Angola", flag: "🇦🇴" },
  { code: "+1268", country: "Antigua and Barbuda", flag: "🇦🇬" },
  { code: "+54", country: "Argentina", flag: "🇦🇷" },
  { code: "+374", country: "Armenia", flag: "🇦🇲" },
  { code: "+297", country: "Aruba", flag: "🇦🇼" },
  { code: "+61", country: "Australia", flag: "🇦🇺" },
  { code: "+43", country: "Austria", flag: "🇦🇹" },
  { code: "+994", country: "Azerbaijan", flag: "🇦🇿" },
  { code: "+1242", country: "Bahamas", flag: "🇧🇸" },
  { code: "+973", country: "Bahrain", flag: "🇧🇭" },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩" },
  { code: "+1246", country: "Barbados", flag: "🇧🇧" },
  { code: "+375", country: "Belarus", flag: "🇧🇾" },
  { code: "+32", country: "Belgium", flag: "🇧🇪" },
  { code: "+501", country: "Belize", flag: "🇧🇿" },
  { code: "+229", country: "Benin", flag: "🇧🇯" },
  { code: "+975", country: "Bhutan", flag: "🇧🇹" },
  { code: "+591", country: "Bolivia", flag: "🇧🇴" },
  { code: "+387", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "+267", country: "Botswana", flag: "🇧🇼" },
  { code: "+55", country: "Brazil", flag: "🇧🇷" },
  { code: "+246", country: "British Indian Ocean Territory", flag: "🇮🇴" },
  { code: "+673", country: "Brunei", flag: "🇧🇳" },
  { code: "+359", country: "Bulgaria", flag: "🇧🇬" },
  { code: "+226", country: "Burkina Faso", flag: "🇧🇫" },
  { code: "+257", country: "Burundi", flag: "🇧🇮" },
  { code: "+855", country: "Cambodia", flag: "🇰🇭" },
  { code: "+237", country: "Cameroon", flag: "🇨🇲" },
  { code: "+1", country: "Canada", flag: "🇨🇦" },
  { code: "+238", country: "Cape Verde", flag: "🇨🇻" },
  { code: "+599", country: "Caribbean Netherlands", flag: "🇧🇶" },
  { code: "+236", country: "Central African Republic", flag: "🇨🇫" },
  { code: "+235", country: "Chad", flag: "🇹🇩" },
  { code: "+56", country: "Chile", flag: "🇨🇱" },
  { code: "+86", country: "China", flag: "🇨🇳" },
  { code: "+57", country: "Colombia", flag: "🇨🇴" },
  { code: "+269", country: "Comoros", flag: "🇰🇲" },
  { code: "+243", country: "Congo (DRC)", flag: "🇨🇩" },
  { code: "+242", country: "Congo", flag: "🇨🇬" },
  { code: "+506", country: "Costa Rica", flag: "🇨🇷" },
  { code: "+225", country: "Côte d’Ivoire", flag: "🇨🇮" },
  { code: "+385", country: "Croatia", flag: "🇭🇷" },
  { code: "+53", country: "Cuba", flag: "🇨🇺" },
  { code: "+599", country: "Curaçao", flag: "🇨🇼" },
  { code: "+357", country: "Cyprus", flag: "🇨🇾" },
  { code: "+420", country: "Czech Republic", flag: "🇨🇿" },
  { code: "+45", country: "Denmark", flag: "🇩🇰" },
  { code: "+253", country: "Djibouti", flag: "🇩🇯" },
  { code: "+1767", country: "Dominica", flag: "🇩🇲" },
  { code: "+1", country: "Dominican Republic", flag: "🇩🇴" },
  { code: "+593", country: "Ecuador", flag: "🇪🇨" },
  { code: "+20", country: "Egypt", flag: "🇪🇬" },
  { code: "+503", country: "El Salvador", flag: "🇸🇻" },
  { code: "+240", country: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "+291", country: "Eritrea", flag: "🇪🇷" },
  { code: "+372", country: "Estonia", flag: "🇪🇪" },
  { code: "+251", country: "Ethiopia", flag: "🇪🇹" },
  { code: "+679", country: "Fiji", flag: "🇫🇯" },
  { code: "+358", country: "Finland", flag: "🇫🇮" },
  { code: "+33", country: "France", flag: "🇫🇷" },
  { code: "+594", country: "French Guiana", flag: "🇬🇫" },
  { code: "+689", country: "French Polynesia", flag: "🇵🇫" },
  { code: "+241", country: "Gabon", flag: "🇬🇦" },
  { code: "+220", country: "Gambia", flag: "🇬🇲" },
  { code: "+995", country: "Georgia", flag: "🇬🇪" },
  { code: "+49", country: "Germany", flag: "🇩🇪" },
  { code: "+233", country: "Ghana", flag: "🇬🇭" },
  { code: "+30", country: "Greece", flag: "🇬🇷" },
  { code: "+1473", country: "Grenada", flag: "🇬🇩" },
  { code: "+590", country: "Guadeloupe", flag: "🇬🇵" },
  { code: "+1671", country: "Guam", flag: "🇬🇺" },
  { code: "+502", country: "Guatemala", flag: "🇬🇹" },
  { code: "+224", country: "Guinea", flag: "🇬🇳" },
  { code: "+245", country: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "+592", country: "Guyana", flag: "🇬🇾" },
  { code: "+509", country: "Haiti", flag: "🇭🇹" },
  { code: "+504", country: "Honduras", flag: "🇭🇳" },
  { code: "+852", country: "Hong Kong", flag: "🇭🇰" },
  { code: "+36", country: "Hungary", flag: "🇭🇺" },
  { code: "+354", country: "Iceland", flag: "🇮🇸" },
  { code: "+91", country: "India", flag: "🇮🇳" },
  { code: "+62", country: "Indonesia", flag: "🇮🇩" },
  { code: "+98", country: "Iran", flag: "🇮🇷" },
  { code: "+964", country: "Iraq", flag: "🇮🇶" },
  { code: "+353", country: "Ireland", flag: "🇮🇪" },
  { code: "+972", country: "Israel", flag: "🇮🇱" },
  { code: "+39", country: "Italy", flag: "🇮🇹" },
  { code: "+1876", country: "Jamaica", flag: "🇯🇲" },
  { code: "+81", country: "Japan", flag: "🇯🇵" },
  { code: "+962", country: "Jordan", flag: "🇯🇴" },
  { code: "+7", country: "Kazakhstan", flag: "🇰🇿" },
  { code: "+254", country: "Kenya", flag: "🇰🇪" },
  { code: "+686", country: "Kiribati", flag: "🇰🇮" },
  { code: "+383", country: "Kosovo", flag: "🇽🇰" },
  { code: "+965", country: "Kuwait", flag: "🇰🇼" },
  { code: "+996", country: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "+856", country: "Laos", flag: "🇱🇦" },
  { code: "+371", country: "Latvia", flag: "🇱🇻" },
  { code: "+961", country: "Lebanon", flag: "🇱🇧" },
  { code: "+266", country: "Lesotho", flag: "🇱🇸" },
  { code: "+231", country: "Liberia", flag: "🇱🇷" },
  { code: "+218", country: "Libya", flag: "🇱🇾" },
  { code: "+423", country: "Liechtenstein", flag: "🇱🇮" },
  { code: "+370", country: "Lithuania", flag: "🇱🇹" },
  { code: "+352", country: "Luxembourg", flag: "🇱🇺" },
  { code: "+853", country: "Macau", flag: "🇲🇴" },
  { code: "+389", country: "Macedonia", flag: "🇲🇰" },
  { code: "+261", country: "Madagascar", flag: "🇲🇬" },
  { code: "+265", country: "Malawi", flag: "🇲🇼" },
  { code: "+60", country: "Malaysia", flag: "🇲🇾" },
  { code: "+960", country: "Maldives", flag: "🇲🇻" },
  { code: "+223", country: "Mali", flag: "🇲🇱" },
  { code: "+356", country: "Malta", flag: "🇲🇹" },
  { code: "+692", country: "Marshall Islands", flag: "🇲🇭" },
  { code: "+596", country: "Martinique", flag: "🇲🇶" },
  { code: "+222", country: "Mauritania", flag: "🇲🇷" },
  { code: "+230", country: "Mauritius", flag: "🇲🇺" },
  { code: "+52", country: "Mexico", flag: "🇲🇽" },
  { code: "+691", country: "Micronesia", flag: "🇫🇲" },
  { code: "+373", country: "Moldova", flag: "🇲🇩" },
  { code: "+377", country: "Monaco", flag: "🇲🇨" },
  { code: "+976", country: "Mongolia", flag: "🇲🇳" },
  { code: "+382", country: "Montenegro", flag: "🇲🇪" },
  { code: "+212", country: "Morocco", flag: "🇲🇦" },
  { code: "+258", country: "Mozambique", flag: "🇲🇿" },
  { code: "+95", country: "Myanmar", flag: "🇲🇲" },
  { code: "+264", country: "Namibia", flag: "🇳🇦" },
  { code: "+674", country: "Nauru", flag: "🇳🇷" },
  { code: "+977", country: "Nepal", flag: "🇳🇵" },
  { code: "+31", country: "Netherlands", flag: "🇳🇱" },
  { code: "+687", country: "New Caledonia", flag: "🇳🇨" },
  { code: "+64", country: "New Zealand", flag: "🇳🇿" },
  { code: "+505", country: "Nicaragua", flag: "🇳🇮" },
  { code: "+227", country: "Niger", flag: "🇳🇪" },
  { code: "+234", country: "Nigeria", flag: "🇳🇬" },
  { code: "+850", country: "North Korea", flag: "🇰🇵" },
  { code: "+47", country: "Norway", flag: "🇳🇴" },
  { code: "+968", country: "Oman", flag: "🇴🇲" },
  { code: "+92", country: "Pakistan", flag: "🇵🇰" },
  { code: "+680", country: "Palau", flag: "🇵🇼" },
  { code: "+970", country: "Palestine", flag: "🇵🇸" },
  { code: "+507", country: "Panama", flag: "🇵🇦" },
  { code: "+675", country: "Papua New Guinea", flag: "🇵🇬" },
  { code: "+595", country: "Paraguay", flag: "🇵🇾" },
  { code: "+51", country: "Peru", flag: "🇵🇪" },
  { code: "+63", country: "Philippines", flag: "🇵🇭" },
  { code: "+48", country: "Poland", flag: "🇵🇱" },
  { code: "+351", country: "Portugal", flag: "🇵🇹" },
  { code: "+1", country: "Puerto Rico", flag: "🇵🇷" },
  { code: "+974", country: "Qatar", flag: "🇶🇦" },
  { code: "+262", country: "Réunion", flag: "🇷🇪" },
  { code: "+40", country: "Romania", flag: "🇷🇴" },
  { code: "+7", country: "Russia", flag: "🇷🇺" },
  { code: "+250", country: "Rwanda", flag: "🇷🇼" },
  { code: "+1869", country: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { code: "+1758", country: "Saint Lucia", flag: "🇱🇨" },
  { code: "+1784", country: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { code: "+685", country: "Samoa", flag: "🇼🇸" },
  { code: "+378", country: "San Marino", flag: "🇸🇲" },
  { code: "+239", country: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦" },
  { code: "+221", country: "Senegal", flag: "🇸🇳" },
  { code: "+381", country: "Serbia", flag: "🇷🇸" },
  { code: "+248", country: "Seychelles", flag: "🇸🇨" },
  { code: "+232", country: "Sierra Leone", flag: "🇸🇱" },
  { code: "+65", country: "Singapore", flag: "🇸🇬" },
  { code: "+421", country: "Slovakia", flag: "🇸🇰" },
  { code: "+386", country: "Slovenia", flag: "🇸🇮" },
  { code: "+677", country: "Solomon Islands", flag: "🇸🇧" },
  { code: "+252", country: "Somalia", flag: "🇸🇴" },
  { code: "+27", country: "South Africa", flag: "🇿🇦" },
  { code: "+82", country: "South Korea", flag: "🇰🇷" },
  { code: "+211", country: "South Sudan", flag: "🇸🇸" },
  { code: "+34", country: "Spain", flag: "🇪🇸" },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "+249", country: "Sudan", flag: "🇸🇩" },
  { code: "+597", country: "Suriname", flag: "🇸🇷" },
  { code: "+268", country: "Swaziland", flag: "🇸🇿" },
  { code: "+46", country: "Sweden", flag: "🇸🇪" },
  { code: "+41", country: "Switzerland", flag: "🇨🇭" },
  { code: "+963", country: "Syria", flag: "🇸🇾" },
  { code: "+886", country: "Taiwan", flag: "🇹🇼" },
  { code: "+992", country: "Tajikistan", flag: "🇹🇯" },
  { code: "+255", country: "Tanzania", flag: "🇹🇿" },
  { code: "+66", country: "Thailand", flag: "🇹🇭" },
  { code: "+670", country: "Timor-Leste", flag: "🇹🇱" },
  { code: "+228", country: "Togo", flag: "🇹🇬" },
  { code: "+676", country: "Tonga", flag: "🇹🇴" },
  { code: "+1868", country: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "+216", country: "Tunisia", flag: "🇹🇳" },
  { code: "+90", country: "Turkey", flag: "🇹🇷" },
  { code: "+993", country: "Turkmenistan", flag: "🇹🇲" },
  { code: "+688", country: "Tuvalu", flag: "🇹🇻" },
  { code: "+256", country: "Uganda", flag: "🇺🇬" },
  { code: "+380", country: "Ukraine", flag: "🇺🇦" },
  { code: "+971", country: "United Arab Emirates", flag: "🇦🇪" },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧" },
  { code: "+1", country: "United States", flag: "🇺🇸" },
  { code: "+598", country: "Uruguay", flag: "🇺🇾" },
  { code: "+998", country: "Uzbekistan", flag: "🇺🇿" },
  { code: "+678", country: "Vanuatu", flag: "🇻🇺" },
  { code: "+39", country: "Vatican City", flag: "🇻🇦" },
  { code: "+58", country: "Venezuela", flag: "🇻🇪" },
  { code: "+84", country: "Vietnam", flag: "🇻🇳" },
  { code: "+967", country: "Yemen", flag: "🇾🇪" },
  { code: "+260", country: "Zambia", flag: "🇿🇲" },
  { code: "+263", country: "Zimbabwe", flag: "🇿🇼" }
];




export const usUniversities = [
    "Arizona State University, Tempe, Arizona (All UG programs), (PG -Thunderbird School of Global Management)",
    "University of Arizona, Tucson, Arizona",
    "Virginia Commonwealth University, Richmond, Virginia (Only UG)",
    "Colorado State University, Fort Collins, Colorado",
    "George Mason University, Fairfax County, Virginia",
    "West Virginia University, Morgantown, West Virginia",
    "Oregon State University, Corvallis, Oregon",
    "University of South Florida, Tampa, Florida",
    "Saint Louis University, St. Louis, Missouri",
    "Washington State University, Pullman, Washington",
    "University of Alabama at Birmingham",
    "Suffolk University, Boston, Massachusetts",
    "Marshall University Huntington, West Virginia",
    "Illinois State University, Normal, Illinois",
    "Drew University, Madison, New Jersey",
    "University of Vermont, Burlington, Vermont (UG & Only PG Pathway)",
    "University of Tulsa, Tulsa, Oklahoma (Only UG)",
    "Baylor University, Waco, Texas (Only UG)",
    "Auburn University, Alabama",
    "University of Utah, Salt Lake City, Utah (Only UG)",
    "University of Illinois at Chicago, Illinois (Only UG)",
    "University of Cincinnati, Ohio",
    "Ohio University, Athens, Ohio (Only UG)",
    "Northeastern University, Boston, Massachusetts -D`Amore-McKim School of Business, The College of Professional Studies (CPS)",
    "Brandeis International Business School (IBS), Waltham, Massachusetts",
    "University of Dayton, Dayton, Ohio",
    "University of Colorado Denver, Colorado",
    "Graduate School at UMBC, University of Maryland, Baltimore County",
    "The City College of New York, New York",
    "University of Albany, The State University of New York, Albany (SUNY Albany)",
    "SUNY Polytechnic Institute, Utica, New York",
    "The State University of New York at New Paltz (SUNY New Paltz)",
    "State University of New York at Fredonia (UG and PG Programs)",
    "State University of New York at Brockport (SUNY Brockport)",
    "State University of New York at Plattsburgh (SUNY Plattsburgh)",
    "State University of New York College at Old Westbury, New York",
    "American University Washington D.C.",
    "University of South Carolina, Columbia, South Carolina",
    "University of the Pacific, Stockton, California (Only UG)",
    "University of Kansas, Lawrence, Kansas (Only UG)",
    "Louisiana State University, Baton Rouge, Louisiana (Only UG)",
    "The University of Nebraska-Lincoln (Only UG)",
    "Missouri University of Science & Technology, Public land grant university in Rolla, Missouri",
    "University of Massachusetts, Lowell, Massachusetts",
    "University of Massachusetts, Dartmouth, Massachusetts (UG/PG Pathway)",
    "University of Massachusetts, Boston, Massachusetts",
    "Massachusetts College of Pharmacy and Health Sciences, Boston, Massachusetts (MCPHS University)",
    "University of New Hampshire, Durham, New Hampshire",
    "Adelphi University, Garden City, New York",
    "University of Central Florida, Orlando, Florida (Only UG)",
    "University of Idaho, Moscow, Idaho",
    "San Jose State University, San Jose, California",
    "San Francisco State University, San Francisco, California",
    "California State University, Northridge",
    "California State University, Fresno",
    "California State University, East Bay",
    "California State University, Channel Islands",
    "California State University, Sacramento",
    "California State University, Bakersfield",
    "California State University, Dominguez Hills",
    "California State University, Stanislaus",
    "California State University, San Bernardino",
    "California State University, Monterey Bay",
    "California Baptist University, Riverside",
    "Sonoma State University, Rohnert Park",
    "New Jersey Institute of Technology, Newark, New Jersey",
    "Florida Institute of Technology, Melbourne, Florida",
    "Pace University, New York",
    "University of Hartford (International Pathway and UG, PG Direct entry)",
    "Florida International University, Miami, Florida",
    "University of St. Thomas, Saint Paul, Minnesota",
    "Kent State University, Kent, Ohio",
    "Loyola University, New Orleans, Louisiana",
    "Nebraska Wesleyan University Lincoln (Only UG)",
    "Mississippi State University, Mississippi",
    "University of New Mexico, Albuquerque",
    "University of Nevada, Reno",
    "Wright State University, Dayton, Ohio",
    "Wichita State University, Wichita, Kansas",
    "Northern Arizona University, Flagstaff, Arizona",
    "University of North Texas, Denton, Texas",
    "University of Missouri–St. Louis (UMSL), Missouri",
    "The University of Memphis, Memphis, Tennessee",
    "Tennessee Tech University, Cookeville, Tennessee",
    "Texas State University, San Marcos, Texas",
    "Florida Atlantic University, Boca Raton, Florida (UG /PG Pathway)",
    "National Louis University, Chicago, Illinois",
    "Montana State University, Bozeman, Montana",
    "Gannon University, Erie, Pennsylvania",
    "Milwaukee School of Engineering, Milwaukee, Wisconsin",
    "Auburn University at Montgomery, Alabama",
    "Long Island University, Post, New York",
    "Long Island University, Brooklyn, New York",
    "Midwestern State University, Wichita Falls, Texas",
    "Texas A & M University, Corpus Christi, Texas",
    "Western Kentucky University, Bowling Green, Kentucky",
    "Southeast Missouri State University, Cape Girardeau, Missouri",
    "Youngstown State University, Youngstown, Ohio",
    "Purdue University Northwest, Hammond and Westville, Indiana, United States",
    "Arkansas State University, Jonesboro, Arkansas",
    "Roosevelt University, Chicago, Illinois",
    "DePaul University (Global Pathway and UG, PG Direct entry)",
    "University of New Haven, West Haven, Connecticut",
    "Humboldt State University, Arcata, California",
    "Widener University, Chester, Pennsylvania",
    "Dakota State University, Madison, South Dakota",
    "Pittsburg State University, Pittsburg, Kansas",
    "University of Bridgeport, Bridgeport, Connecticut",
    "New York Institute of Technology, New York",
    "Murray State University, Murray, Kentucky",
    "Duquesne University, Pittsburgh, Pennsylvania",
    "Quinnipiac University, Hamden, Connecticut",
    "University of Central Oklahoma, Edmond, Oklahoma",
    "Lawrence Technological University, Southfield, Michigan",
    "Saint Leo University, St. Leo, Florida",
    "Johnson & Wales University, Providence, Rhode Island",
    "Northwest Missouri State University, Maryville, Missouri",
    "California Lutheran University, Thousand Oaks, California ( School of Management)",
    "Pacific Lutheran University, Tacoma, Washington (International Pathway and UG, PG programs)",
    "Ashland University, Ashland, Ohio",
    "Indiana State University, Terre Haute, Indiana",
    "University of Tampa, Florida, USA",
    "University of Nebraska, Kearney, Nebraska (only UG)",
    "Mercer University, Macon, Georgia",
    "Southern New Hampshire University, Manchester, New Hampshire",
    "National University, San Diego, California",
    "Troy University, Troy, Alabama",
    "Texas Wesleyan University, Fort Worth, Texas",
    "Dallas Baptist University, Dallas, Texas",
    "Thomas Jefferson University, Philadelphia, Pennsylvania",
    "Western New England University, Springfield, Massachusetts",
    "Rivier University, Nashua, New Hampshire",
    "Missouri Western State University, Missouri",
    "Northwood University, Midland, Michigan (Only UG)",
    "St. Thomas University, Miami Gardens, Florida",
    "Rider University, Lawrenceville, New Jersey",
    "Atlantis University, Miami, Florida",
    "Valparaiso University, Valparaiso, Indiana",
    "Oglethorpe University, Atlanta, Georgia (Only UG)",
    "Saginaw Valley State University, University Center, Michigan",
    "Slippery Rock University, Slippery Rock, Pennsylvania",
    "Trine University, Angola, Indiana",
    "Golden Gate University, San Francisco, California (Only PG)",
    "Marymount California University, Rancho Palos Verdes, California",
    "University of Wisconsin-Eau Claire, Wisconsin",
    "University of Wisconsin–La Crosse, Wisconsin",
    "Charleston Southern University, Charleston, South Carolina",
    "DeVry University, Downers Grove, Illinois",
    "James Madison University, Harrisonburg, Virginia (Only UG)",
    "Tiffin University, Ohio",
    "Academy of Art University, San Francisco, California",
    "Full Sail University, Winter Park, Florida",
    "Kendall College Chicago, Illinois",
    "Cleary University, Howell, Michigan",
    "New York Film Academy, New York City",
    "Upper Iowa University, Fayette, Iowa",
    "Briar Cliff University, Sioux city, Iowa",
    "Oklahoma City University, Oklahoma City, Oklahoma",
    "Webster University, Missouri",
    "The University of Findlay, Findlay, Ohio",
    "Hult International Business School Boston, San Francisco campus",
    "Schiller International University, Largo, Florida",
    "Concordia University Chicago, River Forest, Illinois",
    "University of Mary Hardin-Baylor, Belton, Texas",
    "Lipscomb University, Nashville, Tennessee (Only UG)",
    "Western Washington University, Bellingham, Washington",
    "New England Institute of Technology, East Greenwich, Rhode Island",
    "Marist College, Poughkeepsie, New York",
    "Mississippi College, Clinton, Mississippi",
    "Manhattan College, Riverdale, New York",
    "Monroe College, Bronx, New York",
    "New England College, Henniker, New Hampshire",
    "Stevens Henager College, Salt Lake, Utah (Work- Study Option)",
    "Berkeley College, New York",
    "Rocky Mountain College of Art & Design, Lakewood, Colorado",
    "Canisius College, Buffalo, New York",
    "Bellevue College, Bellevue, Washington",
    "St. Thomas Aquinas College, Sparkill, New York",
    "Richard Bland College of William & Mary, Petersburg, Virginia",
    "Agnes Scott University, Decatur, Georgia",
    "Fisher College, Boston, Massachusetts",
    "Merrimack College, North Andover, Massachusetts (PG Pathway)",
    "Metropolitan College of New York, New York City, New York",
    "Green River Community College, Auburn, Washington",
    "Seattle Central Community College, Seattle, Washington",
    "Shoreline Community College, Washington",
    "Hillsborough Community College, Tampa, Florida",
    "San Mateo College of Silicon Valley, San Mateo, California",
    "Santa Ana College, California",
    "American Honors, Washington, D.C (National Transfer Network)",
    "Colorado Mesa University, Colorado",
    "Husson University, Bangor, Maine",
    "Capital University, Ohio",
    "Metropolitan State University of Denver, Colorado",
    "Manhattanville College, New York",
    "On Campus University of Rochester (UG University Transfer Program)",
    "On Campus University of Rhode Island, Kingston (UG University Transfer Program)",
    "On Campus Boston Wheelock College (UG University Transfer Program)",
    "On Campus California State Monterey Bay (UG University Transfer Program)",
    "On Campus SUNY Morrisville State College (UG University Transfer Program)",
    "On Campus Texas at University of North Texas (UG University Transfer Program)",
    "University of California, Berkeley Extension, California",
    "UCSC Silicon Valley Extension (For Certificate Programs and Pre Sessional English)",
    "University of California, Riverside Extension",
    "Aviation Institute of Maintenance",
    "Drexel University, English Language Center, Philadelphia, Pennsylvania (For ELC Programs)",
    "California State University, Los Angeles (ELP Programs at UG/PG Level)",
    "Kaplan Test Prep, a division of Kaplan",
    "Summer Discovery. Discovery Internship and Jr. Internship."
  ];
  